version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crm_server
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres_container
    networks:
      - mynetwork
      - crm_internal

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: crm_web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - crm_internal
    depends_on:
      - server

networks:
  mynetwork:
    external: true
    name: docker_mynetwork
  crm_internal:
    driver: bridge
